packages:
  - apps/*
  - packages/*
  - presentations/*

catalog:
  '@eslint/css': 0.11.1
  '@eslint/js': 9.36.0
  '@eslint/json': 0.13.2
  '@eslint/markdown': 7.3.0
  '@hono/node-server': 1.19.4
  '@hono/session': 0.2.0
  '@hono/vite-dev-server': 0.21.0
  '@starfederation/datastar-sdk': 1.0.0-RC.1
  '@types/node': 24.5.2
  '@vitest/coverage-v8': 3.2.4
  dotenv: 17.2.2
  eslint: 9.36.0
  eslint-config-prettier: 10.1.8
  eslint-import-resolver-typescript: 4.4.4
  eslint-plugin-prettier: 5.5.4
  globals: 16.4.0
  hono: 4.9.8
  jiti: 2.6.0
  jsdom: 27.0.0
  prettier: 3.6.2
  prettier-plugin-organize-imports: 4.3.0
  tslib: 2.8.1
  typescript: 5.9.2
  typescript-eslint: 8.44.1
  vite: 7.1.7
  vite-plugin-dts: 4.5.4
  vitest: 3.2.4

ignoredBuiltDependencies:
  - esbuild
  - unrs-resolver
