import type { AnimalName } from '@clair-obscur-workspace/domain';

export const ADJECTIVES = [
  // Classic positive
  'Happy',
  'Gentle',
  'Brave',
  'Wise',
  'Kind',
  'Strong',
  'Swift',
  'Bright',
  'Bold',
  'Calm',
  'Clever',
  'Noble',
  'Pure',
  'Wild',
  'Free',
  'Golden',
  'Silver',
  'Crystal',
  'Royal',
  'Sacred',
  // Pedantic/intellectual
  'Erudite',
  'Perspicacious',
  'Sagacious',
  'Discerning',
  'Astute',
  'Cerebral',
  'Pedantic',
  'Verbose',
  'Meticulous',
  'Fastidious',
  'Punctilious',
  'Persnickety',
  'Scholarly',
  'Bookish',
  'Academic',
  'Sophisticated',
  'Cultivated',
  'Refined',
  'Urbane',
  'Cosmopolitan',
  // Funny/quirky
  'Wobbly',
  'Giggly',
  'Snuggly',
  'Bouncy',
  'Dizzy',
  'Fuzzy',
  'Wiggly',
  'Silly',
  'Goofy',
  'Cheeky',
  'Quirky',
  'Zany',
  'Wacky',
  'Bonkers',
  'Loopy',
  'Nutty',
  'Daft',
  'Bonky',
  'Wonky',
  'Funky',
  'Zippy',
  'Peppy',
  'Perky',
  'Bubbly',
  'Jolly',
  'Merry',
  'Chipper',
  'Sprightly',
  'Jaunty',
  'Lively',
  // Mystical
  'Mystical',
  'Ethereal',
  'Cosmic',
  'Celestial',
  'Divine',
  'Magical',
  'Enchanted',
  'Blessed',
  'Luminous',
  'Radiant',
  'Transcendent',
  'Sublime',
  'Arcane',
  'Esoteric',
  'Mysterious',
  'Enigmatic',
  'Prophetic',
  'Omniscient',
  // Colors and textures
  'Crimson',
  'Azure',
  'Emerald',
  'Violet',
  'Amber',
  'Coral',
  'Indigo',
  'Scarlet',
  'Turquoise',
  'Magenta',
  'Velvet',
  'Silky',
  'Glossy',
  'Shimmering',
  'Gleaming',
  'Sparkling',
  'Glowing',
  'Twinkling',
  // Weather/nature
  'Stormy',
  'Misty',
  'Foggy',
  'Dewy',
  'Frosty',
  'Snowy',
  'Rainy',
  'Sunny',
  'Windy',
  'Thunderous',
  // Size/shape
  'Tiny',
  'Massive',
  'Colossal',
  'Miniature',
  'Gigantic',
  'Petite',
  'Enormous',
  'Microscopic',
] as const;

export const ANIMALS = [
  // Classic mammals
  'Lion',
  'Tiger',
  'Bear',
  'Wolf',
  'Fox',
  'Rabbit',
  'Cat',
  'Dog',
  'Horse',
  'Elephant',
  'Giraffe',
  'Zebra',
  'Kangaroo',
  'Panda',
  'Koala',
  'Monkey',
  'Gorilla',
  'Chimpanzee',
  'Orangutan',
  'Lemur',
  'Dolphin',
  'Whale',
  'Seal',
  'Otter',
  'Beaver',
  'Squirrel',
  'Hedgehog',
  'Raccoon',
  'Badger',
  'Skunk',
  // Birds
  'Eagle',
  'Hawk',
  'Owl',
  'Raven',
  'Crow',
  'Robin',
  'Cardinal',
  'Swan',
  'Duck',
  'Goose',
  'Penguin',
  'Flamingo',
  'Peacock',
  'Parrot',
  'Toucan',
  'Hummingbird',
  'Albatross',
  'Pelican',
  // Reptiles/Amphibians
  'Snake',
  'Lizard',
  'Turtle',
  'Tortoise',
  'Iguana',
  'Chameleon',
  'Gecko',
  'Frog',
  'Toad',
  'Salamander',
  'Crocodile',
  'Alligator',
  'Dragon',
  'Komodo',
  // Sea creatures
  'Octopus',
  'Squid',
  'Jellyfish',
  'Shark',
  'Ray',
  'Seahorse',
  'Starfish',
  'Crab',
  'Lobster',
  'Shrimp',
  'Swordfish',
  'Angelfish',
  'Clownfish',
  'Pufferfish',
  // Insects/Arachnids
  'Butterfly',
  'Bee',
  'Ladybug',
  'Dragonfly',
  'Mantis',
  'Spider',
  'Scorpion',
  'Ant',
  'Grasshopper',
  'Cricket',
  // Unexpected/Exotic
  'Axolotl',
  'Capybara',
  'Quokka',
  'Pangolin',
  'Platypus',
  'Narwhal',
  'Manatee',
  'Sloth',
  'Armadillo',
  'Anteater',
  'Tapir',
  'Okapi',
  'Binturong',
  'Fossa',
  'Quetzal',
  'Kiwi',
  'Cassowary',
  'Shoebill',
  'Kakapo',
  'Numbat',
  // Mythical/Magical
  'Unicorn',
  'Phoenix',
  'Griffin',
  'Pegasus',
  'Sphinx',
  'Chimera',
  'Hydra',
  'Kraken',
  'Leviathan',
  'Basilisk',
] as const;

export type Adjective = (typeof ADJECTIVES)[number];
export type Animal = (typeof ANIMALS)[number];

export const AnimalNameFactory = {
  create(adjective?: Adjective, animal?: Animal): AnimalName {
    return {
      adjective: adjective ?? ADJECTIVES[0],
      animal: animal ?? ANIMALS[0],
    };
  },

  random(): AnimalName {
    const adjective: Adjective | undefined =
      ADJECTIVES[Math.floor(Math.random() * ADJECTIVES.length)];
    const animal: Animal | undefined = ANIMALS[Math.floor(Math.random() * ANIMALS.length)];
    return AnimalNameFactory.create(adjective, animal);
  },

  getKey(animalName: AnimalName): string {
    return `${animalName.adjective}_${animalName.animal}`;
  },
};
